// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0IrvebWt-ZwH1TAjoUgbtihpPWoR-vk8',
    appId: '1:358753272653:web:31bba337cd4779cfb86d04',
    messagingSenderId: '358753272653',
    projectId: 'flutter-messanger-b99a3',
    authDomain: 'flutter-messanger-b99a3.firebaseapp.com',
    storageBucket: 'flutter-messanger-b99a3.appspot.com',
    measurementId: 'G-47QE6NKBHT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDENI5eUzI92RD9w-9978Wc49aKiwXeo4c',
    appId: '1:358753272653:android:2a9ef402c44e757bb86d04',
    messagingSenderId: '358753272653',
    projectId: 'flutter-messanger-b99a3',
    storageBucket: 'flutter-messanger-b99a3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgD-IUiNUplZYUp9-8nyS6F5vC3HWWtEo',
    appId: '1:358753272653:ios:b0bfbfd8f0c7ced7b86d04',
    messagingSenderId: '358753272653',
    projectId: 'flutter-messanger-b99a3',
    storageBucket: 'flutter-messanger-b99a3.appspot.com',
    iosClientId: '358753272653-5bbhbegodmj620lv82jj8i4tjk4mlpi2.apps.googleusercontent.com',
    iosBundleId: 'com.example.messenger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgD-IUiNUplZYUp9-8nyS6F5vC3HWWtEo',
    appId: '1:358753272653:ios:b0bfbfd8f0c7ced7b86d04',
    messagingSenderId: '358753272653',
    projectId: 'flutter-messanger-b99a3',
    storageBucket: 'flutter-messanger-b99a3.appspot.com',
    iosClientId: '358753272653-5bbhbegodmj620lv82jj8i4tjk4mlpi2.apps.googleusercontent.com',
    iosBundleId: 'com.example.messenger',
  );
}
